# Generated by Django 5.2.6 on 2025-10-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentchatidmodel',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Chat ID deleted'),
        ),
    ]
