# Generated by Django 5.2.6 on 2025-10-06 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_agentchatidmodel_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentchatidmodel',
            name='chat_name',
            field=models.CharField(default='', max_length=60, verbose_name='Chat name'),
        ),
        migrations.AlterField(
            model_name='agentchatidmodel',
            name='chat_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_id', to=settings.AUTH_USER_MODEL, unique=True, verbose_name='Agent chat id'),
        ),
    ]
