# Generated by Django 5.2.6 on 2025-10-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_agentchatidmodel_chat_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentchatidmodel',
            old_name='chat_id',
            new_name='bubble_user',
        ),
        migrations.AlterField(
            model_name='agentchatidmodel',
            name='chat_name',
            field=models.CharField(default='New Chat', max_length=60, verbose_name='Chat name'),
        ),
    ]
