# Generated by Django 5.2.6 on 2025-10-06 19:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_rename_chat_id_agentchatidmodel_bubble_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentchatidmodel',
            name='chat_id',
            field=models.CharField(default=uuid.uuid4, unique=True, verbose_name='Agent chat id'),
        ),
        migrations.AlterField(
            model_name='agentchatidmodel',
            name='bubble_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bubble_user', to=settings.AUTH_USER_MODEL, verbose_name='Bubble user'),
        ),
    ]
