# Generated by Django 5.2.6 on 2025-10-06 19:07
import uuid

from django.db import migrations

def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model("ai", "AgentChatIDModel")
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_agentchatidmodel_chat_id_and_more'),
    ]

    operations = [
        migrations.RunPython(gen_uuid),
    ]
