# Generated by Django 5.2.6 on 2025-10-06 19:07
import uuid

from django.db import migrations, models

def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model("ai", "AgentChatIDModel")
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])

class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_populate_chat_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentchatidmodel',
            name='chat_id',
            field=models.CharField(default=uuid.uuid4, unique=True, verbose_name='Agent chat id'),
        ),
    ]
