# Generated by Django 5.2.6 on 2025-10-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_auto_20251006_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentchatidmodel',
            name='chat_id',
            field=models.CharField(unique=True, verbose_name='Agent chat id'),
        ),
    ]
