# Generated by Django 5.2.6 on 2025-10-06 19:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0008_alter_agentchatidmodel_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentchatidmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agentchatidmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
