# Generated by Django 5.2.6 on 2025-10-30 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0010_alter_agentchatidmodel_bubble_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_count', models.IntegerField(default=0, verbose_name='Token count')),
                ('token_used', models.IntegerField(default=0, verbose_name='Token used')),
                ('bubble_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bubble_user_token_usage', to=settings.AUTH_USER_MODEL, verbose_name='Bubble user')),
            ],
        ),
    ]
