# Generated by Django 5.2.6 on 2025-10-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0011_tokenusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenusage',
            name='token_count',
            field=models.IntegerField(default=20000, verbose_name='Token count'),
        ),
    ]
