# Generated by Django 5.2.6 on 2026-01-26 11:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0012_alter_tokenusage_token_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenusage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tokenusage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tokenusage',
            name='token_count',
            field=models.IntegerField(default=60000, verbose_name='Token count'),
        ),
    ]
