# Generated by Django 5.2.6 on 2026-01-26 12:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0013_tokenusage_created_at_tokenusage_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenusage',
            name='renewable_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
